import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { CheckCircle2, Plus, Send } from "lucide-react";
import Card from "../../../shared/components/ui/Card";
import Button from "../../../shared/components/ui/Button";
import Badge from "../../../shared/components/ui/Badge";
import Input from "../../../shared/components/ui/Input";
import Textarea from "../../../shared/components/ui/Textarea";
import ProgressBar from "../../../shared/components/ui/ProgressBar";
import { useAuth } from "../../auth/store/AuthContext";
import { projectService } from "../services/projectService";
import StatusTimeline from "../components/StatusTimeline";
import { formatCurrency, formatDate } from "../../../shared/utils/formatters";

export default function ProjectDetail() {
  const { id } = useParams();
  const { user, notify } = useAuth();
  const [project, setProject] = useState(null);
  const [loading, setLoading] = useState(true);
  const reload = () => projectService.getProject(id).then(setProject).finally(()=>setLoading(false));
  useEffect(()=>{ reload(); }, [id]);
  const advance = async () => { const res = await projectService.advanceStatus(id); setProject(res.project); notify(res.message); };
  if (loading) return <div className="h-96 animate-pulse rounded-3xl bg-white/[0.045]" />;
  if (!project) return <div className="rounded-3xl bg-white/[0.035] p-10 text-center">Project not found.</div>;
  const fundingProgress = project.fundingGoal ? (project.currentFunding / project.fundingGoal) * 100 : 0;
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge tone="green">{project.status}</Badge><h1 className="xini-heading-lg mt-4">{project.title}</h1><p className="mt-2 max-w-3xl text-sm xini-muted">{project.synopsis}</p></div>{["creator","admin"].includes(user.role) && <Button onClick={advance}><Send size={16}/>Move to next status</Button>}</div><Card><StatusTimeline status={project.status}/></Card><div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="space-y-6"><Card><h2 className="xini-heading-md">Project overview</h2><p className="mt-4 text-sm leading-7 xini-muted">{project.description}</p><div className="mt-6 grid gap-4 md:grid-cols-3"><Info label="Genre" value={project.genre}/><Info label="Language" value={project.language}/><Info label="Runtime" value={`${project.runtime || 0} min`}/><Info label="Lifecycle" value={project.lifecycleStage}/><Info label="Budget" value={formatCurrency(project.budget)}/><Info label="Visibility" value={project.visibility}/></div></Card><StudioPackageCard project={project}/><TeamPanel project={project} onChange={setProject}/><MilestonePanel project={project} onChange={setProject}/><UpdatesPanel project={project} onChange={setProject}/></div><aside className="space-y-6"><Card><h2 className="xini-heading-md">Funding status</h2><div className="mt-5"><div className="mb-2 flex justify-between text-sm"><span className="text-white/55">Raised</span><span>{Math.round(fundingProgress)}%</span></div><ProgressBar value={fundingProgress}/></div><div className="mt-5 space-y-3"><Info label="Current funding" value={formatCurrency(project.currentFunding)}/><Info label="Funding goal" value={formatCurrency(project.fundingGoal)}/></div></Card><Card><h2 className="xini-heading-md">Lifecycle summary</h2><div className="mt-5 space-y-3 text-sm"><Row label="Created" value={formatDate(project.createdAt)}/><Row label="Updated" value={formatDate(project.updatedAt)}/><Row label="Team" value={`${project.team?.length || 0} members`}/><Row label="Milestones" value={`${project.milestones?.length || 0} total`}/><Row label="Updates" value={`${project.updates?.length || 0} posts`}/></div></Card></aside></div></div>;
}

function StudioPackageCard({ project }) { const studio = project.studio || {}; const docs = studio.documents || []; return <Card><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="xini-heading-md">Creator Studio package</h2><p className="mt-1 text-sm xini-muted">Brief, AI pitch summary, and investor documents from Creator Studio Lite.</p></div><Link to={`/studio?project=${project.id}`}><Button variant="secondary" size="sm">Open studio</Button></Link></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Info label="Logline" value={studio.brief?.logline || "Not added"}/><Info label="Pitch summary" value={studio.pitchSummary || "Not generated"}/><Info label="Documents" value={`${docs.length}/4 uploaded`}/><Info label="Positioning" value={studio.brief?.positioning || "Not added"}/></div></Card>; }
function Info({ label, value }) { return <div className="rounded-2xl bg-white/[0.035] p-4"><p className="text-xs text-white/40">{label}</p><p className="mt-1 break-words font-medium capitalize">{value}</p></div>; }
function Row({ label, value }) { return <div className="flex justify-between border-b border-white/[0.05] pb-2"><span className="text-white/45">{label}</span><span>{value}</span></div>; }
function TeamPanel({ project, onChange }) { const { notify } = useAuth(); const [form,setForm]=useState({name:"",role:"",bio:"",profileUrl:""}); const [open,setOpen]=useState(false); const submit=async(e)=>{e.preventDefault(); if(!form.name||!form.role)return; const res=await projectService.addTeamMember(project.id,form); onChange(res.project); notify(res.message); setForm({name:"",role:"",bio:"",profileUrl:""}); setOpen(false);}; return <Card><div className="flex items-center justify-between"><div><h2 className="xini-heading-md">Team management</h2><p className="mt-1 text-sm xini-muted">Add and view production team members.</p></div><Button variant="secondary" size="sm" onClick={()=>setOpen(!open)}><Plus size={15}/>Add</Button></div>{open&&<form onSubmit={submit} className="mt-5 grid gap-3 md:grid-cols-2"><Input label="Name" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/><Input label="Role" value={form.role} onChange={(e)=>setForm({...form,role:e.target.value})}/><Textarea label="Bio" className="md:col-span-2" value={form.bio} onChange={(e)=>setForm({...form,bio:e.target.value})}/><div className="md:col-span-2"><Button type="submit" size="sm">Save member</Button></div></form>}<div className="mt-5 grid gap-3 md:grid-cols-2">{(project.team||[]).map(m=><div key={m.id} className="rounded-2xl border border-white/[0.06] bg-white/[0.035] p-4"><p className="font-medium">{m.name}</p><p className="text-sm text-xini-mint">{m.role}</p><p className="mt-2 text-xs leading-6 text-white/45">{m.bio || "No bio added."}</p></div>)}</div></Card>; }
function MilestonePanel({ project, onChange }) { const { notify }=useAuth(); const [open,setOpen]=useState(false); const [form,setForm]=useState({title:"",description:"",dueDate:"",fundingReleasePercentage:""}); const submit=async(e)=>{e.preventDefault(); if(!form.title)return; const res=await projectService.addMilestone(project.id,form); onChange(res.project); notify(res.message); setForm({title:"",description:"",dueDate:"",fundingReleasePercentage:""}); setOpen(false);}; const toggle=async(ms)=>{const res=await projectService.toggleMilestone(project.id,ms.id); onChange(res.project); notify(res.message);}; return <Card><div className="flex items-center justify-between"><div><h2 className="xini-heading-md">Project milestones</h2><p className="mt-1 text-sm xini-muted">Track production and funding milestones.</p></div><Button variant="secondary" size="sm" onClick={()=>setOpen(!open)}><Plus size={15}/>Add</Button></div>{open&&<form onSubmit={submit} className="mt-5 grid gap-3 md:grid-cols-2"><Input label="Title" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><Input label="Due date" type="date" value={form.dueDate} onChange={(e)=>setForm({...form,dueDate:e.target.value})}/><Input label="Funding release %" type="number" value={form.fundingReleasePercentage} onChange={(e)=>setForm({...form,fundingReleasePercentage:e.target.value})}/><Textarea label="Description" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/><div className="md:col-span-2"><Button type="submit" size="sm">Save milestone</Button></div></form>}<div className="mt-5 space-y-3">{(project.milestones||[]).map(ms=><button key={ms.id} onClick={()=>toggle(ms)} className="w-full rounded-2xl border border-white/[0.06] bg-white/[0.035] p-4 text-left transition hover:border-xini-green/30"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{ms.title}</p><p className="mt-1 text-xs text-white/45">Due {formatDate(ms.dueDate)} · {ms.fundingReleasePercentage}% release</p></div><Badge tone={ms.status==="completed"?"success":ms.status==="in_progress"?"warning":"muted"}>{ms.status}</Badge></div><p className="mt-2 text-xs leading-6 text-white/45">{ms.description}</p></button>)}</div></Card>; }
function UpdatesPanel({ project, onChange }) { const { notify }=useAuth(); const [form,setForm]=useState({title:"",body:""}); const submit=async(e)=>{e.preventDefault(); if(!form.title||!form.body)return; const res=await projectService.addUpdate(project.id,form); onChange(res.project); notify(res.message); setForm({title:"",body:""});}; return <Card><h2 className="xini-heading-md">Project updates</h2><p className="mt-1 text-sm xini-muted">Publish timeline updates for stakeholders.</p><form onSubmit={submit} className="mt-5 grid gap-3"><Input label="Update title" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><Textarea label="Update message" value={form.body} onChange={(e)=>setForm({...form,body:e.target.value})}/><div><Button type="submit" size="sm">Publish update</Button></div></form><div className="mt-6 space-y-3">{(project.updates||[]).map(up=><div key={up.id} className="rounded-2xl border border-white/[0.06] bg-white/[0.035] p-4"><p className="font-medium">{up.title}</p><p className="mt-1 text-xs text-white/40">{formatDate(up.createdAt)}</p><p className="mt-2 text-sm leading-7 text-white/55">{up.body}</p></div>)}</div></Card>; }
